[package]
name = "rpgbe"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "0.1.15"
sdl2 = "0.35.1"
